### ISSUE TITLE
LameXP.2015-10-23.Release-Static.Build-1818.exe   causes crash

### ISSUE THREAD

**Issue by foggyxp** [lordmulder/LameXP#27] opened 2015-10-26 07:33 UTC
update or new installation trial with  LameXP.2015-10-23.Release-Static.Build-1818.exe  (v4.12)
causes blue screen-crash during installation process (antivirus disabled, windows 7 pro 64 bit).
This never happend with older versions.
Starting LameXP.exe out of the estracted zip-File works well.

**Comment by lordmulder** [comment] 2015-10-26 19:15
I have no idea. Actually, *user-space* programs, like LameXP or the LameXP setup program, can **not** cause BSoD (Blue Screen of Death) – neither accidentally nor willingly – because they do **not** have *kernel-mode* privileges. Would pretty dreadful, if a single program could crash the whole system.

So, if you encounter BSoD, this either because of a bug in the *operating system* itself, or, more likely, the fault of a buggy *device driver*. Well, it could also be a *hardware* issue, e.g. corrupted memory module. Anyway, if the BSoD occurred while installing LameXP, then this was just a coincidence – a symptom of some other problem. LameXP or the LameXP installer are **not** the actual cause of the problem.

Having said that: Is the problem *reproducible*, i.e. does it happen *every time* that you try to install LameXP **r1818**? And does it happen *never* when you install LameXP **r1700**? This would be pretty weird, because the installer doesn't do anything special. It's just a pretty boring NSIS installer. And the changes to the installer between **r1700** and **r1818** are minimal.

**Comment by foggyxp** [comment] 2015-10-28 09:06
I tried   LameXP.2015-10-23.Release-Static.Build-1818.exe  several times, always resulting in BSoD. So right now I tried  LameXP.2015-04-05.Release-Static.Build-1700.exe  -> no problem. I have no idea of the problem. Runnig LameXP.exe v4.12 out of the zip-File is ok.


Windows7 Pro restart-Information after BSoD:

Problemsignatur:
  Problemereignisname:	BlueScreen
  Betriebsystemversion:	6.1.7601.2.1.0.256.48
  Gebietsschema-ID:	2055

Zusatzinformationen zum Problem:
  BCCode:	3b
  BCP1:	00000000C0000005
  BCP2:	0000000000000000
  BCP3:	FFFFF88011EC0000
  BCP4:	0000000000000000
  OS Version:	6_1_7601
  Service Pack:	1_0
  Product:	256_1

**Comment by lordmulder** [comment] 2015-10-29 19:35
Almost certainly not a LameXP-related issue:

> Bugcheck code: **0x3B** (0xC0000005, 0xFFFFF8032131983F, 0xFFFFD0002562EE60, 0x0)
> Error: SYSTEM_SERVICE_EXCEPTION
> file path: C:\WINDOWS\system32\ntoskrnl.exe
> product: Microsoft® Windows® Operating System
> company: Microsoft Corporation
> description: NT Kernel & System
> Bug check description: This indicates that an exception happened while executing a routine that transitions from non-privileged code to privileged code.
> This appears to be a typical software **driver bug** and is not likely to be caused by a hardware problem.
> The crash took place in the **Windows kernel**. Possibly this problem is caused by another driver that cannot be identified at this time.

**Comment by lordmulder** [comment] 2015-11-07 17:55
As there seems to be no indication that anything is wrong on LameXP's side, I'm gonna close this one.

**Closed by lordmulder** 2015-11-07 17:55 UTC
Labels: Non-Issue
