### ISSUE TITLE
LameXP complains about updates in 2020 on startup.

### ISSUE THREAD

**Issue by hardlycode** [lordmulder/LameXP#94] opened 2021-01-13 03:14 UTC
For some reason every time I start LameXP, it insists on checking for updates even though I've done so a dozen times this year. Disabling "check for updates" does nothing. It still insists on checking every time.

(Great software, by the way. Just the constant update check is annoying.)

**Comment by lordmulder** [comment] 2021-01-13 19:34
Sorry, this happens because current version is more than a year old. A 

Being trapped in the home office for ~1 year now doesn't exactly add to my motivation, but new version will be released soon™.

In the meantime you can test the latest release candidate:
https://sourceforge.net/projects/lamexp/files/Snapshots%20%28BETA%29/2020-12-22/

Regards.

**Comment by hardlycode** [comment] 2021-01-14 12:43
Oh that's definitely no problem! I was just concerned that the "skip update" check button was actually broken.

Thank you for the release candidate. I've installed it and I'll see if I can find any bugs for you.

**Comment by isidroco** [comment] 2021-05-04 15:16
Well it IS a bug that both checking: Disable Sound Effects and Disable Update Reminder are completly ignored, because when skipping update an very annoying loud music plays through my system, volume is always very loud on my studio because we use low Db levels for high DR and all system sound are disabled for that reason, so LameXP usage is now forbidden because of that.

**Comment by lordmulder** [comment] 2021-05-04 15:38
The option to disable the Update Reminder, which will *suggest* checking for updates 14 days after the previous update check – *never* LameXP will contact the update server without the user's consent – is completely ***unrelated*** to the built-in "expiry date" after which *old* versions will more firmly ask for an update. You can **not** turn off the built-in "expiry date" in an existing binary, only create a "fresh" binary from the original source codes. This is a countermeasure against annoying software sites that are still offering 5+ years old builds of my software as the so-called "latest" version – and stoically ignoring update requests.

**Comment by isidroco** [comment] 2021-05-04 15:51
Well, hope new version doesn't have any sounds when Disable Sound Effect is checked,  update reminder it's not so intrusive, although maybe it should refrain to recheck for one week after no updates found.

**Comment by lordmulder** [comment] 2021-05-04 16:05
> Well, hope new version doesn't have any sounds when Disable Sound Effect is checked

Unless I still missed some sound, which I hope not, it should be like that. You can check the latest test build, if you like:
[LameXP-RC5.2021-04-22.Release-Static.Build-2305.exe](https://sourceforge.net/projects/lamexp/files/Snapshots%20%28BETA%29/2021-04-22/LameXP-RC5.2021-04-22.Release-Static.Build-2305.exe/download)

> update reminder it's not so intrusive, although maybe it should refrain to recheck for one week after no updates found.

The Update Reminder can be disabled, as always. Nothing has changed about this. The "expire date" also still works as it always  used to, for the reason pointed out in my previous reply, except that the TTL has been increased from 12 to 15 months.

**Comment by AzzaAzza69** [comment] 2021-05-07 06:52
It appears the yearly update check is triggers only if the year is different as I vaguely remember it activating in Jan 2020 but the build is Dec 2019?

I would also suggest introducing a day difference check between the "forced update check" as if the program is used & closed repeatedly, it checks EVERY TIME the program is launched.

**Comment by hardlycode** [comment] 2021-05-07 09:45
I honestly don't see the point of this check to begin with. There's enough
trouble with commercial software becoming unusable due to abandonment by
companies. Why add a timer to this program?

I mean, it works perfectly fine for me and I've had no trouble with it
EXCEPT this constant update check...

Sincerely,
Jonathan

**Comment by isidroco** [comment] 2021-05-07 17:30
> Unless I still missed some sounds, which I hope not, it should be exactly like that.
> 
> You can check the latest test build, if you like:
> [LameXP-RC5.2021-04-22.Release-Static.Build-2305.exe](https://sourceforge.net/projects/lamexp/files/Snapshots%20%28BETA%29/2021-04-22/LameXP-RC5.2021-04-22.Release-Static.Build-2305.exe/download)
> 
> > update reminder it's not so intrusive, although maybe it should refrain to recheck for one week after no updates found.
> 
> The "Update Reminder" can be disabled, as always. Nothing has changed about this.

I don't install RC or beta versions on my working PC. So as it is now, "Update Reminder" uncheck doesn't refrain expiricy date to trigger, I wil start using runasdate to circunvect this (IMO stupid) feature which also triggers annoying and imposible to disable sound. 
Hope a new definitive non beta version where these issues are solved comes soon.

**Comment by lordmulder** [comment] 2021-05-07 17:58
> I don't install RC or beta versions on my working PC

Well, fair enough. But the more people try out pre-release versions and help to find possible regressions, the more "stable" the next release will be for everyone. Also, you don't even need to "install". Just grab the ZIP and extract it anywhere you like.

**Comment by highqualitymusic** [comment] 2021-07-26 06:35
Hi Lordmulder, 
I also find the reminder for the "built-in expired binary" very annoying. 

You wrote: "You can not turn off the built-in "expiry date" in an existing binary, only build a "fresh" binary from the original source codes. And that is exactly the purpose. It is primarily a countermeasure against those annoying software sites that are still offering 5+ years old builds of my software as what they call the "latest" version"
This argument does not work for me. Because the daily annoying "build expired" ringing does not hit the providers of outdated versions, it hits the user! 
To create a new build from the source files "just now" or to find someone competent for it is only "easy" from a programmer's point of view. It requires a certain amount of expertise and / or good contacts. I have neither the one nor the other. The user needs much less knowledge to take care of downloading the latest version of a software on his own responsibility - if possible directly at the source! I find the latter much easier.

So please change your mind and give us users the choice! Please redesign the software so that users can choose whether and how to be reminded that they are using an outdated version.
Suggestions: 
If the date has expired, the program shows the following message **under the Lame-XP-Logo at startup** 
"OUTDATED VERSION - please update!"
**In the title bar of the software** this text also appears next to the software title.

As an option for those. who like to be reminded also with sound (but this should be selectable and deselectable!)
Reminder with sound can be replaced by user (The volume level of the cut-off Geopardy is killing my monitors, since I usually listen to music which is recorded without loudness war ambitions).

It seems that I'm not the only one with this wish.

I would spend some dozens of money to solve this issue.

**Comment by isidroco** [comment] 2021-07-27 14:00
The problem is that some of us only use Final releases. There's no way now to use a final release without receiving that LOUD warning (my monitors are usually at a VERY high volume). Maybe you should make a new final version identical to the previous one with a longer expire date. And PLEASE low all the levels at least 10dB. Thanks.

**Comment by lordmulder** [comment] 2021-07-27 14:56
> The problem is that some of us only use Final releases. There's no way now to use a final release without receiving that LOUD warning (my monitors are usually at a VERY high volume).

It was never supposed to happen that you get that message - and cannot update to a new stable release.

(Also, as said before, in current version you _can_ disable **all** sounds)

> Maybe you should make a new final version identical to the previous one with a longer expire date. And PLEASE low all the levels at least 10dB. Thanks.

If the release of the next "final" version wasn't imminent, this would be an option. As things are, hopefully not needed.

**Comment by highqualitymusic** [comment] 2021-07-27 16:15
Professional Audio Soundcards do not have such a feature like "smart volume" since we do not want to listen to music that is compressed by some blackbox compressing algorithm.
So my B&W loudspeakers nearly "pop off the box" since the Geopardy-Audio has ugly mpeg artifacts and high distortion.
Please consider that the next final version might again take more than 15 months! 
A permanent OPTICAL warning like "UPDATE is urgently needed" should be sufficient to warn us users - but PLEASE without annoiying with ugly and loud audio that cuts our musical ears and without delaying the usage of the software.
I really feel this as patronizing.

**Comment by highqualitymusic** [comment] 2021-07-27 16:20
> This has already been addressed for the upcoming release:
> [7179ad1](https://github.com/lordmulder/LameXP/commit/7179ad161ee9a9bc84cabbe02c7db1facc35dbf0)
> 
What comes under the link is too complicated for me. As a programmer, you may see it differently, but I prefer to invest my time in listening to music, making music and recording sound.

**Comment by highqualitymusic** [comment] 2021-07-27 16:23
> (Yes, "should". Because, this time around, it didn't quite work out like I planned. There are a few more things I need to look into, but just haven't found the time/motivation yet. Sometimes real life kicks in, you know?)

Oh yes. I understand that. 
So one more reason to take the pressure off boith sides and extend the time until the annoying warning to at least 24 months.

**Comment by lordmulder** [comment] 2021-07-29 16:42
> Professional Audio Soundcards do not have such a feature like "smart volume" since we do not want to listen to music that is compressed by some blackbox compressing algorithm.

Turn off "volume normalization" with one click, if you plan listinening to a longer recording that has consistent volume 😏 

(For anything else, like television, youtube, video calls, games, etc. pp. it is a real lifesaver)

> What comes under the link is too complicated for me. As a programmer, you may see it differently, but I prefer to invest my time in listening to music, making music and recording sound.

This is Github. So better get used to people pointing to the relevant commit when it comes to discussing problem and/or fixes 🤣

**Comment by Scharnvirk** [comment] 2021-08-05 06:47
I too vote for removing this feature, since from user's standpoint this is simply a bug: option supposed to do A is not doing A, and option supposed to do B is not doing B. Simple as that, regardless of the rationale behind. 

I got the software right from github in 2019 IIRC, and I've been satisfied with it since. Because there were far too many cases of some various apps I've been using which were broken by an update, my default policy is to update software when I need it, not when it needs it; unless there are security updates. There is nothing worse than a broken workflow because a new version, and honestly, LameXP with two very apparent bugs doesn't really spark confidence: "yeah better not update, if those 2 checkboxes are not working who knows what is broken in next release? At least major functionality works, I can live with those".

Now that I've read this thread I understand what's going on and I'll update, I'd just like to add another vote that this issue.

**Comment by hardlycode** [comment] 2021-08-05 08:39
To everyone on this thread:

I would like to being by saying I understand the maintainer/author's point
of view on this matter: supporting old versions of software that are/could
be broken is a huge waste of time for software maintainers.

That said:

1. This is 2021. People know they have a responsibility to maintain their
own software/computer systems is now common knowledge among most people,
even if they don't do it.

2. I've spent hours, if not days, setting up virtual machines and
maintaining old equipment for not just myself but people around me because
software no longer works on newer systems or the licensing system is broken
thus disabling the software.

Examples:

A. Driver based PDF printing applications that became unusable on newer
OSes.
B. Various CAD applications that need hardware dongles.
C. Torrent software that crippled the free version to push people to buy a
newer commercial version.
D. Various professional image editing programs that will not be named are
just a few examples of this.

3. The USER, not the author of the software, assumes the risk by running
old and outdated software.

4. If the author wishes only to release their software and not support it
via forums/email, that is also the author's prerogative.

5. Any software bundled with ads, crypto mining, search engines or other
annoyances to generate profit for the authors eventually become crippled
over time leading to increased maintenance which is usually performed BY
PEOPLE WHO KNOW WHAT THEY ARE DOING BUT DON'T GET PAID FOR IT ANYWAY.

I, personally, started collecting software and keeping backups of
installation files from over 30 years ago. I still have software that only
runs on Windows 98, XP, or 32bit-only systems that I occasionally use.

That said: intentionally crippling software, especially open source
software, in ANY way, is irresponsible and is in opposition to what open
source software is supposed to be.

With all due respect.

Jonathan

**Comment by highqualitymusic** [comment] 2021-08-05 12:51
> 
> 
> > Well, hope new version doesn't have any sounds when Disable Sound Effect is checked
> 
> Unless I still missed some sounds, which I hope not, it should be exactly like that.
> 
> You can check the latest test build, if you like:
> [LameXP-RC5.2021-04-22.Release-Static.Build-2305.exe](https://sourceforge.net/projects/lamexp/files/Snapshots%20%28BETA%29/2021-04-22/LameXP-RC5.2021-04-22.Release-Static.Build-2305.exe/download)
> 
> > update reminder it's not so intrusive, although maybe it should refrain to recheck for one week after no updates found.
> 
With this version and the actual LameXP-RC11.2021-07-26.Release-Static.Build-2317
I get TROJAN reported on LameXP.exe or lxp_curl.exe or lxp_verify.exe an the LameXP debug console-generated TEMP folder!
The original verify.exe and the curl.exe are free of viruses, I checked them by virustotal.

**Comment by hardlycode** [comment] 2021-08-05 12:54
Which anti-virus software did you detect this with?

Can you post screenshots of JUST the virus information?

**Comment by highqualitymusic** [comment] 2021-08-05 13:01
LOOK and COMMENT HERE for further details: #100

**Comment by highqualitymusic** [comment] 2021-08-05 15:16
> My "Sound Blaster **Pro**" sure does rofl
Pro Soundcards start here: https://www.thomann.de/gb/audio_interfaces1.html
They use ASIO and it's annoying to do seven things to enable it (and this is just the shortest way to do so!) and another seven steps to disable it - each time!!! :vomiting_face: 
1. Click self-made link to sound.cpl
2. Scroll down though several outputs 
3. Select RME audio channel 
4. Click Properties
5. Click Enhancements Tab
6. Tick Loudness Equalization
7. Click OK
(8. Click active window)

And for many pro audio / musicians soundcards / audio interfaces this won't work. Yes, you *can* tick "Loudness Equalization" but it will have just no effect since ASIO takes the most direct way from CPU to audio out.
ASIO is *the* common standard for all devices musicians, producers and pro audio girls and guys do work with.
We would have to take another ten clicks to switch to WASPI or DirectSound driver which causes quite a mess and clicks to all digital systems behind. And another ten click to switch back. 
> 
> This is Github.
> So better get used to people pointing to the relevant commit when it comes to discussing problems and/or fixes cold_sweat
:disappointed: Sound like "Eat or die bird!"
> 
> Anyway, the takeaway is this: It already has been fixed (a while ago) in the current version.  
:+1:

**Comment by hardlycode** [comment] 2021-08-18 18:41
https://lordmulder.github.com/LameXP

You need to fix your link on github...

**Comment by lordmulder** [comment] 2021-08-29 17:24
Fixed in #56ddb1133b279a3ec29da91a20a9424b7a0273a4.

**Closed by lordmulder** 2021-08-29 17:24 UTC
Labels: Investigating

**Comment by lordmulder** [comment] 2021-08-29 19:50
> https://lordmulder.github.com/LameXP
> 
> You need to fix your link on github...

Can you clarify, where exactly did you find the "wrong" link? 😕

**Comment by hardlycode** [comment] 2021-08-29 23:26
Sorry, https://github.com/lordmulder/LameXP

The link on the right side of the page points to
http://lordmulder.github.com/LameXP

**Comment by lordmulder** [comment] 2021-08-30 21:41
> The link on the right side of the page points to http://lordmulder.github.com/LameXP
Oh, I see. Fixed now.
