### ISSUE TITLE
the virus problem

### ISSUE THREAD

**Issue by Butterfly-Dragon** [lordmulder/LameXP#98] opened 2021-07-16 08:23 UTC
right now i either install the one version that is more than one and a half years old... which mocks me for not updating (please remove _the very idea of such a thing_ from any and all future versions, **_especially_** since you cannot deliver 1 version per year)...

...or even baseline windows refuses to acknowledge that your version of curl is not a virus.

![image](https://user-images.githubusercontent.com/33538906/125914929-3b611ecc-e70b-4cc5-b4ca-d47c2dd1bf7b.png)

I litterally have to fight the operative system each time i start your software because it sees your version of curl as a freaking virus.

I don't know why you need a weird version of curl to check stuff online...
do you really have to check for new versions each time?
why can't you use baseline windows curl to check for new versions?
If you are worried that curl is not part of the windows install why not make a pop up to install the stuff that you need?

I get that this is a free software, but man...
...do not nag people telling them it is their fault that your stuff does not work for stuff you refuse to do for... whatever it is your reason.
I am sure there is a valid reason.
It's just completely hidden and obscure to me.
So my empathy is currently reaching negative levels.

**Comment by lordmulder** [comment] 2021-07-21 19:45
> right now i either install the one version that is more than one and a half years old... which mocks me for not updating

A new version will be released soon™. The "expiry" time has already been increased for the upcoming release.

> ...or even baseline windows refuses to acknowledge that your version of curl is not a virus.
> I litterally have to fight the operative system each time i start your software because it sees your version of curl as a freaking virus.

As annoying as this may be, this is **not** the right place for reporting bugs in the so-called "anti-virus" software that is preventing your system from functioning correctly. You'll have to report the problem to the "anti-virus" vendor :expressionless:

_Recommended reading:_
http://lamexp.sourceforge.net/doc/Manual.html#anti-virus-notes

> I don't know why you need a weird version of curl to check stuff online...

It's **not** a "weird" version, but a 100% legitimate version!

cURL is free/libre software. Also, building software ourselves, from the source codes, applying any changes that we may possibly desire, not only is 100% legitimate but also is our ***fundamental right***. As soon as we give that right up, e.g. to because so-called "anti-virus" software doesn't "allow" us to run our own custom binaries anymore, the idea of "free software" is dead! Not on my watch :angry:

You can find build script for cURL, including all the required dependencies here:

BTW: Building a **fully-static** binary of cURL that has all the required dependencies *built-in* that that runs without any additional runtime dependencies on **all** versions of windows down to Windows XP was quite a journey!

>  why can't you use baseline windows curl to check for new versions?

Because LameXP is a *fully self-contained* software that runs on Windows XP or later.

And because "my" cURL binary comes with support for TLS 1.3 and HTTP/2 ***without*** depending on the WinHTTP or SChannel libraries of Windows. It has the latest version of OpenSSL built-in.

**Comment by lordmulder** [comment] 2021-07-21 20:02
> right now i either install the one version that is more than one and a half years old... which mocks me for not updating

A new version will be released soon™. The "expiry" time has already been increased for the upcoming release.

> ...or even baseline windows refuses to acknowledge that your version of curl is not a virus.
> I litterally have to fight the operative system each time i start your software because it sees your version of curl as a freaking virus.

As annoying as this may be, this is **not** the right place for reporting bugs in the so-called "anti-virus" software that is preventing your system from functioning correctly. You'll have to report the problem to the "anti-virus" vendor :expressionless:

_Recommended reading:_
http://lamexp.sourceforge.net/doc/Manual.html#anti-virus-notes

> do you really have to check for new versions each time?

LameXP ***never*** checks for new versions without the user's consent. It *suggests* checking for a new version every 14 days.

(*very old* versions of LameXP will "expire" and more eagerly ask for an update. But that's a whole other thing)

> I don't know why you need a weird version of curl to check stuff online...

It's **not** a "weird" version. *My* binary of cURL (or yours!) is as legitimate as any other cURL binary! :satisfied:

cURL is free/libre software. Also, building software ourselves, from the source codes, and applying any changes that we may possibly desire not only is 100% legitimate but also is our ***fundamental right***. As soon as we give that right up, e.g. because so-called "anti-virus" software is trying to suppress us, then the idea of "free software" is dead! Not on my watch :angry:

You can find *my* build script for cURL, including all the required dependencies, here:
https://sourceforge.net/projects/muldersoft/files/cURL/Build/curl-winbuild.2021-06-20.zip/download

**BTW:** Building a *fully-static* binary of cURL that has all the required dependencies *built-in* and that runs, *without* any additional runtime dependencies, on ***all*** versions of Windows, down to Windows XP, was quite a journey!

>  why can't you use baseline windows curl to check for new versions?

Because LameXP is a *fully self-contained* software that runs on Windows XP or later. And because "my" cURL binary comes with support for TLS 1.3 and HTTP/2 ***without*** depending on the WinHTTP or SChannel libraries of the Windows operating system. It instead has the latest version of OpenSSL *built-in*. Only way to get *up-to-date* TLS on somewhat older Windows versions!

> ...do not nag people telling them it is their fault that your stuff does not work for stuff you refuse to do for... whatever it is your reason.

I do **not** nag anybody. But if so-called "anti-virus" is preventing your computer from working correctly – by blocking ***100% legitimate*** software – then I do **not** try to workaround the symptom but instead Iwill tell you the real cause of the problem.

Please do not shoot the messenger 😏

**Comment by lordmulder** [comment] 2021-07-21 20:32
> right now i either install the one version that is more than one and a half years old... which mocks me for not updating

A new version will be released soon™. The "expiry" time has already been increased for the upcoming release.

> ...or even baseline windows refuses to acknowledge that your version of curl is not a virus.
> I litterally have to fight the operative system each time i start your software because it sees your version of curl as a freaking virus.

As annoying as this may be, this is **not** the right place for reporting bugs in the so-called "anti-virus" software that is preventing your system from functioning correctly. You'll have to report the problem to the "anti-virus" vendor :expressionless:

_Recommended reading:_
http://lamexp.sourceforge.net/doc/Manual.html#anti-virus-notes

> do you really have to check for new versions each time?

LameXP ***never*** checks for new versions without the user's consent. It only *suggests* checking for a new version every 14 days.

*Very old* versions of LameXP will "expire" and then more eagerly ask for an update. That's a whole other thing.

Of course, at the time when the previous release expires, a new "stable" version should already be available. If you want to blame me for anything, then blame me for not releasing a new "stable" version in time. But, yeah, sometimes real life kicks in...

> I don't know why you need a weird version of curl to check stuff online...

It's **not** a "weird" version. *My* binary of cURL (or yours!) is as legitimate as any other cURL binary! :satisfied:

cURL is free/libre software. Also, building software ourselves, from the source codes, and applying any changes that we may possibly desire, not only is 100% legitimate but also is our ***fundamental right***. As soon as we give that right up, e.g. because so-called "anti-virus" software is trying to suppress our freedom, then the idea of "free software" is dead! Not on my watch :angry:

You can find *my* build script for cURL, including all the required dependencies, here:
https://sourceforge.net/projects/muldersoft/files/cURL/Build/curl-winbuild.2021-06-20.zip/download

**BTW:** Building a *fully-static* binary of cURL that has all the required dependencies *built-in* and that runs, *without* any additional runtime dependencies, on ***all*** versions of Windows (down to Windows XP) was quite a journey!

>  why can't you use baseline windows curl to check for new versions?

Because LameXP is a *fully self-contained* software that runs on Windows XP or later. And because "my" cURL binary comes with support for TLS 1.3 and HTTP/2 ***without*** depending on the WinHTTP or SChannel libraries of the Windows operating system. It instead has the latest version of OpenSSL *built-in*. Only way to get *up-to-date* TLS on somewhat older Windows versions!

> ...do not nag people telling them it is their fault that your stuff does not work for stuff you refuse to do for... whatever it is your reason.

I do **not** nag anybody. But if so-called "anti-virus" software is preventing your computer from working correctly – by blocking ***100% legitimate*** software – then I certainly do **not** try to workaround the symptom. Instead I will tell you the cause of the problem.

Please do not shoot the messenger 😏 

As an aside: I currently run Windows 10 (21H1) with the standard Windows Defender enabled on my "main" development machine. So far, I haven't encountered any Windows Defender-related problems concerning any of "my" binaries yet.

(My "work" notebook runs Sophos anti-virus, because of company policy – constant pain!)

Best regards.

**Comment by Butterfly-Dragon** [comment] 2021-07-21 20:39
Dude.
I'm not saying that free software is dead.
Far from it and i love passionate people who work on a project.

But if you are asking us all to:
• unprotect us from you, so that you can protect us all by yourself.
• stay updated, but the updates create hassle, and the non-updated stuff mocks us for not updating.

Then "you are doing it wrong"™:
• You are refusing to use the common stuff we know how to secure and protect by ourselves. So that you can you the "new and better" stuff that actually does not add that much that we were not already adding via a baseline protective layer, but also looks a lot like a virus to everybody and their cousin.
• You are trying to protect the user from the user's choices and tell the user choosing what the user chose is wrong.
• You are trying to manage the user and tell the user you know better than the user. Without knowing the user. Like you told me to read the very faq i started this very post after reading because it angered me. You chose to disregard any and all best practices and then you tell me i should "fight the system". Dude. I'm not fighting the system to be mocked by an updating software that singsongs me and wastes my time if i don't want to check for updates because i do not want to waste time updating something that i judged by myself and declared was not broken enough to need fixing with any update. But unless your damn curl loads then you make me quit the program even if you could use fallbacks which might not be 100% optimal but get the job done without headaches. And you assume i did not secure those fallbacks in some way.
• And all of that goes against my personal principles. I'm against all religions and all the mess they bring.

In general you are telling me to die for you on the hill of your choice. For a freaking pimped up curl. That's like selling me a car with tap water which will stop and play a mocking song if it does not have access to a pipeline. Telling me that having tap water in your car is "essential", and even when attached to the pipeline it will stop and start mocking me if i don't update to your newest version of your personal pipeline attachment system that is more secure and filters the tap water better... except it does so on a freaking clock and does not actually do so if you have or have not developed this newer and better version

I already said i'm against all religions and all the mess they bring. You're not a messenger, you're an advocate and a crusader. Quixote it the way you want it but don't drag me in your personal fights. I'm done fighting other people's crusades for zero rewards. Most of the times the auto-updater is the first thing i disable because i want control over what i use not stuff that runs rampantly by itself like some deranged robot that slams into the first knee high wall and then tries to brute force it via shuffling.

Been using your software since 10/11 years ago. Was fond of it. Has served me well. Gonna switch to Fre:AC. Never used that one before but i'm pretty sure it won't mock me for not updating a software when i don't feel i need updates and and does not forces me to work around the updating system telling me it's "for the freedom of the people" and if i want to not update the software... like most stuff... it will probably have a freaking checkbox that says "stop nagging you silly pile of 0s and 1s and leave the control to me". ¯\_(-_-)_/¯ Been using all sorts of weird stuff on my system only yours does that.

**Closed** 2021-07-26 16:18 UTC
Labels: Non-Issue
